clone:
  git:
    image: plugins/git
    tags: true

workspace:
  base: /go
  path: src/github.com/naveego/plugin-pub-test

pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - src/github.com/naveego/plugin-pub-test/vendor
      - ../../../../pkg/dep
    volumes:
      - /tmp/cache:/cache

  build:
    image: docker.naveego.com:4333/build-go:latest
    pull: true
    environment:
      - CGO_ENABLED=0
    commands:
      - pwd
      - ls 
      - dep ensure -vendor-only      
      - ls vendor
    when:
      event: [ push, pull_request ]

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - src/github.com/naveego/plugin-pub-test/vendor
      - ../../../../pkg/dep
    volumes:
      - /tmp/cache/plugin-pub-test:/cache
    when:
      status:  [ failure, success ]