clone:
  git:
    image: plugins/git
    tags: true

workspace:
  base: /go
  path: src/github.com/naveego/plugin-pub-test

pipeline:

  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - vendor
    volumes:
      - /tmp/cache:/cache

  build:
    image: docker.naveego.com:4333/build-go:latest
    pull: true
    environment:
      - CGO_ENABLED=0
      - GOPATH=/go
    commands:
      - pwd
      - echo $GOPATH
      - go env
      - ls 
      - dep ensure -vendor-only      
      - go build

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - vendor
    volumes:
      - /tmp/cache:/cache
    when:
      status:  [ failure, success ]
